apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csb-producer-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/smongiar/developer-charts
    targetRevision: HEAD
    path: spring-boot-pipeline
    helm:
      values: |
        domain: smongiar
        system: smongiar
        component: csb-producer
  destination:
    server: https://kubernetes.default.svc
    namespace: smongiar-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m